import 'package:flutter/material.dart';

class AchievementEntry {
  const AchievementEntry({
    required this.title,
    required this.description,
    required this.icon,
    this.isUnlocked = false,
  });

  final String title;
  final String description;
  final IconData icon;
  final bool isUnlocked;
}

const vitalisAchievementsCatalog = <AchievementEntry>[
  AchievementEntry(title: 'Primeiro Passo', description: 'Adicione seu primeiro hábito.', icon: Icons.flag_rounded, isUnlocked: true),
  AchievementEntry(title: 'Mestre dos Hábitos', description: 'Adicione mais de 5 hábitos.', icon: Icons.emoji_events_rounded),
  AchievementEntry(title: 'Dia Perfeito', description: 'Complete sua rotina por 1 dia.', icon: Icons.wb_sunny_rounded),
  AchievementEntry(title: 'Constância Inicial', description: 'Complete sua rotina por 1 semana.', icon: Icons.calendar_view_week_rounded),
  AchievementEntry(title: 'Disciplina em Ação', description: 'Complete sua rotina por 2 semanas.', icon: Icons.insights_rounded),
  AchievementEntry(title: 'Rotina de Ferro', description: 'Complete sua rotina por 1 mês.', icon: Icons.fitness_center_rounded),
  AchievementEntry(title: 'Persistente', description: 'Complete sua rotina por 2 meses.', icon: Icons.autorenew_rounded),
  AchievementEntry(title: 'Inabalável', description: 'Complete sua rotina por 3 meses.', icon: Icons.shield_rounded),
  AchievementEntry(title: 'Exemplo de Disciplina', description: 'Complete sua rotina por 4 meses.', icon: Icons.workspace_premium_rounded),
  AchievementEntry(title: 'Lenda da Consistência', description: 'Complete sua rotina por 5 meses.', icon: Icons.local_fire_department_rounded),
  AchievementEntry(title: 'Meio Ano de Glória', description: 'Complete sua rotina por 6 meses.', icon: Icons.stars_rounded),
  AchievementEntry(title: 'Ano Transformador', description: 'Complete sua rotina por 1 ano.', icon: Icons.rocket_launch_rounded),
  AchievementEntry(title: 'Caminho da Fé', description: 'Adicione um hábito religioso.', icon: Icons.church_rounded),
  AchievementEntry(title: 'Fé Inabalável', description: 'Mantenha hábitos religiosos por 1 semana.', icon: Icons.volunteer_activism_rounded),
  AchievementEntry(title: 'Corredor Iniciante', description: 'Corra mais de 10 km.', icon: Icons.directions_run_rounded),
  AchievementEntry(title: 'Poliglota em Formação', description: 'Inicie o aprendizado de outro idioma.', icon: Icons.translate_rounded),
  AchievementEntry(title: 'Pedalando Longe', description: 'Pedale mais de 10 km.', icon: Icons.pedal_bike_rounded),
  AchievementEntry(title: 'Hidratação Perfeita', description: 'Conclua sua meta diária de consumo de água.', icon: Icons.water_drop_rounded, isUnlocked: true),
  AchievementEntry(title: 'Projeto Shape', description: 'Frequente a academia por 1 semana.', icon: Icons.fitness_center_rounded),
  AchievementEntry(title: 'Vida Fitness', description: 'Frequente a academia por 1 mês.', icon: Icons.sports_gymnastics_rounded),
  AchievementEntry(title: 'Amizades em Dia', description: 'Conclua compromissos sociais com amigos.', icon: Icons.groups_rounded),
  AchievementEntry(title: 'Mente Saudável', description: 'Cuide da saúde mental realizando consultas com psicólogos.', icon: Icons.psychology_rounded),
  AchievementEntry(title: 'Membro Premium', description: 'Assine o plano Premium.', icon: Icons.diamond_rounded),
  AchievementEntry(title: 'Primeira Conexão', description: 'Adicione seu primeiro amigo.', icon: Icons.person_add_alt_1_rounded),
  AchievementEntry(title: 'Competidor Nato', description: 'Inicie uma competição com seus amigos.', icon: Icons.sports_score_rounded),
  AchievementEntry(title: 'Campeão da Semana', description: 'Vença uma competição semanal com seus amigos.', icon: Icons.military_tech_rounded),
  AchievementEntry(title: 'Estudioso', description: 'Estude mais de 7 horas em uma semana.', icon: Icons.menu_book_rounded),
  AchievementEntry(title: 'Aluno Dedicado', description: 'Inicie um hábito de estudo.', icon: Icons.school_rounded),
  AchievementEntry(title: 'Perfil Completo', description: 'Conclua todos os dados cadastrais.', icon: Icons.assignment_turned_in_rounded),
  AchievementEntry(title: 'Peixe na Água', description: 'Nade mais de 10 km.', icon: Icons.pool_rounded),
  AchievementEntry(title: 'Autocontrole', description: 'Realize jejum intermitente.', icon: Icons.spa_rounded),
  AchievementEntry(title: 'Madrugador', description: 'Faça uma atividade física durante a madrugada.', icon: Icons.wb_twilight_rounded, isUnlocked: true),
  AchievementEntry(title: 'XP Hunter', description: 'Ganhe mais de 1000 XP em uma semana.', icon: Icons.bolt_rounded),
  AchievementEntry(title: 'Rumo à Prata', description: 'Alcance a Divisão Prata.', icon: Icons.workspace_premium_outlined),
  AchievementEntry(title: 'Brilho Dourado', description: 'Alcance a Divisão Ouro.', icon: Icons.workspace_premium_rounded),
  AchievementEntry(title: 'Elite Platina', description: 'Alcance a Divisão Platina.', icon: Icons.auto_awesome_rounded),
  AchievementEntry(title: 'Diamante Supremo', description: 'Alcance a Divisão Diamante.', icon: Icons.diamond_outlined),
  AchievementEntry(title: 'O Campeão', description: 'Alcance a Divisão Campeão.', icon: Icons.emoji_events_rounded),
  AchievementEntry(title: 'Rei da Arena', description: 'Permaneça na Divisão Campeão por 1 semana.', icon: Icons.castle_rounded),
  AchievementEntry(title: 'Lenda Viva', description: 'Permaneça na Divisão Campeão por 1 mês.', icon: Icons.history_edu_rounded),
  AchievementEntry(title: 'Sonho Realizado', description: 'Organize e conclua a viagem dos seus sonhos.', icon: Icons.flight_takeoff_rounded),
  AchievementEntry(title: 'Investidor do Futuro', description: 'Inicie uma meta financeira.', icon: Icons.savings_rounded),
  AchievementEntry(title: 'Meio Caminho Andado', description: 'Conclua 50% da sua meta financeira.', icon: Icons.trending_up_rounded),
  AchievementEntry(title: 'Objetivo Alcançado', description: 'Conclua sua meta financeira.', icon: Icons.paid_rounded),
  AchievementEntry(title: 'Explorador da Natureza', description: 'Inicie um hábito de trilhas.', icon: Icons.terrain_rounded),
  AchievementEntry(title: 'Aventureiro Bronze', description: 'Conclua metas semanais de trilha, corrida ou ciclismo.', icon: Icons.hiking_rounded),
  AchievementEntry(title: 'Aventureiro Prata', description: 'Conclua metas semanais de trilha, corrida ou ciclismo por 2 semanas.', icon: Icons.landscape_rounded),
  AchievementEntry(title: 'Aventureiro Ouro', description: 'Conclua metas semanais de trilha, corrida ou ciclismo por 3 semanas.', icon: Icons.park_rounded),
  AchievementEntry(title: 'Primeira Página', description: 'Inicie um hábito de leitura.', icon: Icons.auto_stories_rounded),
  AchievementEntry(title: 'Leitor Dedicado', description: 'Leia um livro completo.', icon: Icons.library_books_rounded),
  AchievementEntry(title: 'Devorador de Livros', description: 'Leia mais de 10 livros em um ano.', icon: Icons.local_library_rounded),
  AchievementEntry(title: 'Leitura Relâmpago', description: 'Conclua um livro em menos de 1 mês.', icon: Icons.flash_on_rounded),
  AchievementEntry(title: 'Semana Radiante', description: 'Mantenha o humor feliz ou radiante durante 1 semana.', icon: Icons.sentiment_very_satisfied_rounded),
  AchievementEntry(title: 'Influenciador Social', description: 'Adicione mais de 5 amigos à sua rede.', icon: Icons.campaign_rounded),
  AchievementEntry(title: 'Diário Vivo', description: 'Registre hábitos e suas conclusões no diário.', icon: Icons.menu_book_rounded),
  AchievementEntry(title: 'Premium Lendário', description: 'Seja assinante Premium por 1 ano.', icon: Icons.workspace_premium_rounded),
  AchievementEntry(title: 'Conectado', description: 'Conecte sua conta ao Google.', icon: Icons.link_rounded),
  AchievementEntry(title: 'Coruja Produtiva', description: 'Conclua 2 ou mais atividades no período noturno.', icon: Icons.nightlight_round_rounded),
  AchievementEntry(title: 'Conquistador Supremo', description: 'Conclua todas as conquistas do aplicativo.', icon: Icons.verified_rounded),
  AchievementEntry(title: 'Colecionador de Conquistas', description: 'Conclua 50% ou mais das conquistas disponíveis.', icon: Icons.collections_bookmark_rounded),
  AchievementEntry(title: 'Leitor Vitalis', description: 'Leia 1 livro da biblioteca Vitalis Premium.', icon: Icons.chrome_reader_mode_rounded),
  AchievementEntry(title: 'Criador de Rotinas', description: 'Adicione um hábito customizado.', icon: Icons.add_task_rounded),
  AchievementEntry(title: 'Constância de Elite', description: 'Mantenha-se acima de 500 XP semanais durante 1 mês.', icon: Icons.timeline_rounded),
  AchievementEntry(title: 'Alta Performance', description: 'Mantenha o índice de métricas semanais acima de 70%.', icon: Icons.query_stats_rounded),
  AchievementEntry(title: 'Fênix', description: 'Retorne ao aplicativo após 30 dias sem utilizá-lo.', icon: Icons.restart_alt_rounded),
  AchievementEntry(title: 'Maratonista', description: 'Complete hábitos por 100 dias consecutivos.', icon: Icons.run_circle_rounded),
  AchievementEntry(title: 'Insone Produtivo', description: 'Conclua atividades após as 3 horas da manhã.', icon: Icons.bedtime_off_rounded),
  AchievementEntry(title: 'Velocista', description: 'Conclua 10 hábitos em um único dia.', icon: Icons.speed_rounded),
  AchievementEntry(title: 'Socializador', description: 'Participe de 10 competições com amigos.', icon: Icons.diversity_3_rounded),
  AchievementEntry(title: 'Zen Master', description: 'Pratique meditação e cuide da sua paz interior.', icon: Icons.self_improvement_rounded, isUnlocked: true),
];
